<a href="https://colab.research.google.com/github/lavaeagle2/colab/blob/practisepds/Automobile_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# Exploratory Data Analysis (EDA) is a important step in data analysis which focuses on understanding patterns, trends and relationships through statistical tools and visualizations. Python offers various libraries like pandas, numPy, matplotlib, seaborn and plotly which enables effective exploration and insights generation to help in further modeling and analysis. Some common EDA techniques are:

    Data Inspection: Check the size of the dataset, how it is organized, the types of data it contains and basic summary values.
    Handling Missing and Duplicate Data: Find and fix empty values or repeated rows to keep the data clean.
    Univariate Analysis: Study one variable at a time to understand its distribution, trend and outliers.
    Bivariate Analysis: Compare two variables to see how they are related.
    Multivariate Analysis: Analyze three or more variables together to understand deeper relationships.
```

**Group by Mechanics**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Automobile_data.csv")
df.head()
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

As you can see there are multiple columns with categoical variable. Using groupby() function lets group these data set on the basis of body-style.

In [ ]:
#groups dataframe according to body-style and prints the keys of groups
df.groupby('body-style').groups.keys()

dict_keys(['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'])

In [ ]:
style = df.groupby('body-style')
print(df["body-style"].value_counts())
#To print the values contained in group convertible
#style.get_group("convertible")

body-style
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64

In [ ]:
double_grouping = df.groupby(["body-style","drive-wheels"])
print(double_grouping.size())
print(double_grouping.head(2))

body-style   drive-wheels
convertible  fwd              1
             rwd              5
hardtop      fwd              1
             rwd              7
hatchback    4wd              2
             fwd             49
             rwd             19
sedan        4wd              3
             fwd             57
             rwd             36
wagon        4wd              4
             fwd             12
             rwd              9
dtype: int64
     symboling normalized-losses           make fuel-type aspiration  \
0            3                 ?    alfa-romero       gas        std
1            3                 ?    alfa-romero       gas        std
2            1                 ?    alfa-romero       gas        std
3            2               164           audi       gas        std
4            2               164           audi       gas        std
5            2                 ?           audi       gas        std
7            1                 ?           audi       gas        std
9            0                 ?           audi       gas      turbo
10           2               192            bmw       gas        std
11           0               192            bmw       gas        std
18           2               121      chevrolet       gas        std
19           1                98      chevrolet       gas        std
28          -1               110          dodge       gas        std
46           2                 ?          isuzu       gas        std
68          -1                93  mercedes-benz    diesel      turbo
69           0                93  mercedes-benz    diesel      turbo
74           1                 ?  mercedes-benz       gas        std
98           2               168         nissan       gas        std
109          0                 ?         peugot       gas        std
140          2                83         subaru       gas        std
144          0               102         subaru       gas        std
148          0                85         subaru       gas        std
149          0                85         subaru       gas      turbo
189          3                 ?     volkswagen       gas        std

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
5            two        sedan          fwd           front        99.8  ...
7           four        wagon          fwd           front       105.8  ...
9            two    hatchback          4wd           front        99.5  ...
10           two        sedan          rwd           front       101.2  ...
11          four        sedan          rwd           front       101.2  ...
18           two    hatchback          fwd           front        88.4  ...
19           two    hatchback          fwd           front        94.5  ...
28          four        wagon          fwd           front       103.3  ...
46           two    hatchback          rwd           front        96.0  ...
68          four        wagon          rwd           front       110.0  ...
69           two      hardtop          rwd           front       106.7  ...
74           two      hardtop          rwd           front       112.0  ...
98           two      hardtop          fwd           front        95.1  ...
109         four        wagon          rwd           front       114.2  ...
140          two    hatchback          4wd           front        93.3  ...
144         four        sedan          4wd           front        97.0  ...
148         four        wagon          4wd           front        96.9  ...
149         four        wagon          4wd           front        96.9  ...
189          two  convertible          fwd           front        94.5  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19     3.4              10.0        102
4            136         mpfi  3.19     3.4               8.0        115
5            136         mpfi  3.19     3.4               8.5        110
7            136         mpfi  3.19     3.4               8.5        110
9            131         mpfi  3.13     3.4               7.0        160
10           108         mpfi   3.5     2.8               8.8        101
11           108         mpfi   3.5     2.8               8.8        101
18            61         2bbl  2.91    3.03               9.5         48
19            90         2bbl  3.03    3.11               9.6         70
28           122         2bbl  3.34    3.46               8.5         88
46           119         spfi  3.43    3.23               9.2         90
68           183          idi  3.58    3.64              21.5        123
69           183          idi  3.58    3.64              21.5        123
74           304         mpfi   3.8    3.35               8.0        184
98            97         2bbl  3.15    3.29               9.4         69
109          120         mpfi  3.46    3.19               8.4         97
140          108         2bbl  3.62    2.64               8.7         73
144          108         2bbl  3.62    2.64               9.0         82
148          108         2bbl  3.62    2.64               9.0         82
149          108         mpfi  3.62    2.64               7.7        111
189          109         mpfi  3.19     3.4               8.5         90

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
5        5500       19          25  15250
7        5500       19          25  18920
9        5500       16          22      ?
10       5800       23          29  16430
11       5800       23          29  16925
18       5100       47          53   5151
19       5400       38          43   6295
28       5000       24          30   8921
46       5000       24          29  11048
68       4350       22          25  28248
69       4350       22          25  28176
74       4500       14          16  45400
98       5200       31          37   8249
109      5000       19          24  12440
140      4400       26          31   7603
144      4800       24          25   9233
148      4800       23          29   8013
149      4800       23          23  11694
189      5500       24          29  11595

[24 rows x 26 columns]

In [ ]:
double_grouping = df.groupby(["body-style","drive-wheels"])
print(double_grouping.obj.head())
#To print the first values contained in each group
#double_grouping.first()

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two
1          3                 ?  alfa-romero       gas        std          two
2          1                 ?  alfa-romero       gas        std          two
3          2               164         audi       gas        std         four
4          2               164         audi       gas        std         four

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130
1  convertible          rwd           front        88.6  ...          130
2    hatchback          rwd           front        94.5  ...          152
3        sedan          fwd           front        99.8  ...          109
4        sedan          4wd           front        99.4  ...          136

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21
1         mpfi  3.47    2.68               9.0        111      5000       21
2         mpfi  2.68    3.47               9.0        154      5000       19
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18

  highway-mpg  price
0          27  13495
1          27  16500
2          26  16500
3          30  13950
4          22  17450

[5 rows x 26 columns]

In [ ]:
# max() will print the maximum entry of each group
style['normalized-losses'].max()
# min() will print the minimum entry of each group
style['normalized-losses'].min()

body-style
convertible    134
hardtop        134
hatchback      101
sedan          102
wagon          103
Name: normalized-losses, dtype: object

In [ ]:

# style['normalized-losses'].min() will print output in series
style['normalized-losses'].min()

# style[['normalized-losses']].min() will print output in data frame
style[['normalized-losses']].min()

            normalized-losses
body-style
convertible               134
hardtop                   134
hatchback                 101
sedan                     102
wagon                     103

In [ ]:
# mean() will print mean of numerical column in each group
LEN = df.groupby('length')
LEN.mean(numeric_only=True)

,symboling,wheel-base,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
length,,,,,,,,,
141.1,2.000000,88.4,60.3,53.2,1488.000000,61.000000,9.5,47.000000,53.000000
144.6,2.000000,86.6,63.9,50.8,1766.000000,92.000000,9.4,40.000000,46.000000
150.0,1.000000,93.7,64.0,52.6,1911.000000,87.666667,9.5,32.666667,36.666667
155.9,0.666667,94.5,63.6,52.0,1885.666667,90.000000,9.6,38.000000,43.000000
156.9,2.000000,93.7,63.4,53.7,2050.000000,97.000000,9.0,31.000000,36.000000
...,...,...,...,...,...,...,...,...,...
198.9,0.000000,114.2,68.4,58.2,3357.500000,136.000000,14.7,22.000000,24.500000
199.2,1.000000,112.0,72.0,55.4,3715.000000,304.000000,8.0,14.000000,16.000000
199.6,0.000000,113.0,69.6,52.8,4066.000000,258.000000,8.1,15.000000,19.000000
202.6,-1.000000,115.6,71.7,56.4,3755.000000,208.500000,14.9,19.000000,21.500000
208.1,0.000000,120.9,71.7,56.7,3900.000000,308.000000,8.0,14.000000,16.000000

In [ ]:
# get mean of each column of specific group
style.get_group('convertible').mean(numeric_only=True)
style.groups(numeric_only=True)

TypeError: 'PrettyDict' object is not callable

In [ ]:
# get the sum of the price for each body-style group
print(pd.to_numeric(style['price'], errors='coerce').obj.head())

0    13495
1    16500
2    16500
3    13950
4    17450
Name: price, dtype: object

In [ ]:
# get the number of symboling/records in each group
style['symboling'].count()
double_grouping = df.groupby(["body-style","symboling"])
print(double_grouping.size())

body-style   symboling
convertible   2            1
              3            5
hardtop       0            1
              1            1
              2            4
              3            2
hatchback    -1            2
              0            8
              1           27
              2           13
              3           20
sedan        -2            3
             -1           13
              0           43
              1           23
              2           14
wagon        -1            7
              0           15
              1            3
dtype: int64

# Merging on Index

In [ ]:
from IPython.display import display_html

def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [ ]:
import pandas as pd

left1 = pd.DataFrame({'key': ['apple','ball','apple', 'apple', 'ball', 'cat'], 'value': range(6)})
right1 = pd.DataFrame({'group_val': [33.4, 5]}, index=['apple', 'ball'])
display_side_by_side(left1,right1)

df1 = pd.merge(left1, right1, left_on='key', right_index=True)
df1

     key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0

In [ ]:
df2 = pd.merge(left1, right1, left_on='key', right_index=True, how='outer')
df2

     key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0
5    cat      5        NaN

# Concatenating along an axis

In [ ]:
import numpy as np

yarra = np.arange(15).reshape((3,5))
yarra

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
 np.concatenate([yarra, yarra], axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

**Data Aggregation**

In [ ]:

# new dataframe that consist length,width,height,curb-weight and price
new_dataset = df.filter(["length","width","height","curb-weight"],axis=1)
new_dataset

     length  width  height  curb-weight
0     168.8   64.1    48.8         2548
1     168.8   64.1    48.8         2548
2     171.2   65.5    52.4         2823
3     176.6   66.2    54.3         2337
4     176.6   66.4    54.3         2824
..      ...    ...     ...          ...
200   188.8   68.9    55.5         2952
201   188.8   68.8    55.5         3049
202   188.8   68.9    55.5         3012
203   188.8   68.9    55.5         3217
204   188.8   68.9    55.5         3062

[205 rows x 4 columns]

In [ ]:

# applying single aggregation for mean over the columns
new_dataset.agg("mean", axis="rows")

length          174.049268
width            65.907805
height           53.724878
curb-weight    2555.565854
dtype: float64

In [ ]:
# applying aggregation sum and minimun across all the columns
new_dataset.agg(['sum', 'min'])

NameError: name 'new_dataset' is not defined

In [ ]:
# find aggregation for these columns
new_dataset.aggregate({"length":['sum', 'min','max'],
              "width":['max', 'min', 'sum'],
              "height":['min', 'sum'],
              "curb-weight":['sum']})
# if any specific aggregation is not applied on a column
# then it has NaN value corresponding to it

      length    width   height  curb-weight
sum  35680.1  13511.1  11013.6     523891.0
min    141.1     60.3     47.8          NaN
max    208.1     72.3      NaN          NaN

In [ ]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [ ]:
df['price'].loc[df['price'].str.isnumeric() == False]

9      ?
44     ?
45     ?
129    ?
Name: price, dtype: object

In [ ]:
price = df['price'].loc[df['price'] != '?']
pmean = price.astype(str).astype(int).sum()
print(pmean/201)

13207.129353233831

In [ ]:
df['price'].str.isnumeric().value_counts()
df['price'].loc[df['price'].str.isnumeric() == False]
price = df['price'].loc[df['price'] != '?']
pmean = price.astype(str).astype(int).mean()
df['price'] = df['price'].replace('?',pmean).astype(int)

df.groupby(["body-style","drive-wheels"]).agg({'height': min, 'length': max, 'price': 'mean'})

                          height  length         price
body-style  drive-wheels
convertible fwd             55.6   159.3  11595.000000
            rwd             48.8   180.3  23949.600000
hardtop     fwd             53.3   162.4   8249.000000
            rwd             51.6   199.2  24202.714286
hatchback   4wd             52.0   178.2  10405.000000
            fwd             49.4   186.6   8396.387755
            rwd             49.6   183.5  14278.263158
sedan       4wd             54.3   176.6  12647.333333
            fwd             50.6   192.7   9930.929825
            rwd             47.8   208.1  21711.833333
wagon       4wd             54.9   173.6   9095.750000
            fwd             53.0   192.7   9997.333333
            rwd             54.1   198.9  16994.222222

**Group-wise operations**

In [ ]:

# Group the data frame df by body-style and drive-wheels and extract stats from each group
df.groupby(
   ["body-style","drive-wheels"]
).agg(
    {
         'height': min,    # minimum height of car in each group
         'length': max,  # maximum length of car in each group
         'price': 'min',  # average price of car in each group

    }
)

<ipython-input-56-109984c15077>:4: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  ).agg(
<ipython-input-56-109984c15077>:4: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ).agg(

                          height  length  price
body-style  drive-wheels
convertible fwd             55.6   159.3  11595
            rwd             48.8   180.3  13495
hardtop     fwd             53.3   162.4   8249
            rwd             51.6   199.2  11199
hatchback   4wd             52.0   178.2   7603
            fwd             49.4   186.6  10595
            rwd             49.6   183.5  10945
sedan       4wd             54.3   176.6  11259
            fwd             50.6   192.7  10245
            rwd             47.8   208.1  11900
wagon       4wd             54.9   173.6  11694
            fwd             53.0   192.7  10198
            rwd             54.1   198.9  12440

In [ ]:
# create dictionary of aggregrations
my_aggregations=(
    {
         'height':min,    # minimum height of car in each group
         'length': max,  # maximum length of car in each group
         'price': 'min',  # average price of car in each group

    }
)
# implementing aggregations in groups
df.groupby(
   ["body-style","drive-wheels"]
).agg(my_aggregations)

<ipython-input-57-24374bcab69e>:13: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  ).agg(my_aggregations)
<ipython-input-57-24374bcab69e>:13: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ).agg(my_aggregations)

                          height  length  price
body-style  drive-wheels
convertible fwd             55.6   159.3  11595
            rwd             48.8   180.3  13495
hardtop     fwd             53.3   162.4   8249
            rwd             51.6   199.2  11199
hatchback   4wd             52.0   178.2   7603
            fwd             49.4   186.6  10595
            rwd             49.6   183.5  10945
sedan       4wd             54.3   176.6  11259
            fwd             50.6   192.7  10245
            rwd             47.8   208.1  11900
wagon       4wd             54.9   173.6  11694
            fwd             53.0   192.7  10198
            rwd             54.1   198.9  12440

We can use numpy functions in aggregation as well

In [ ]:
# import the numpy library as np
import numpy as np
# using numpy libraries for operations
df.groupby(
   ["body-style","drive-wheels"])["length"].agg([np.sum, np.mean, np.std])

<ipython-input-59-00a4f9a237d2>:5: FutureWarning: The provided callable <function sum at 0x7f4d703b4360> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ["body-style","drive-wheels"])["length"].agg([np.sum, np.mean, np.std])
<ipython-input-59-00a4f9a237d2>:5: FutureWarning: The provided callable <function mean at 0x7f4d703b5440> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ["body-style","drive-wheels"])["length"].agg([np.sum, np.mean, np.std])
<ipython-input-59-00a4f9a237d2>:5: FutureWarning: The provided callable <function std at 0x7f4d703b5580> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  ["body-style","drive-wheels"])["length"].agg([np.sum, np.mean, np.std])

                             sum        mean        std
body-style  drive-wheels
convertible fwd            159.3  159.300000        NaN
            rwd            863.0  172.600000   5.357705
hardtop     fwd            162.4  162.400000        NaN
            rwd           1253.1  179.014286  10.861465
hatchback   4wd            335.5  167.750000  14.778532
            fwd           8033.3  163.944898  11.029885
            rwd           3292.7  173.300000   4.931644
sedan       4wd            520.6  173.533333   2.655811
            fwd           9793.3  171.812281   8.482757
            rwd           6734.3  187.063889   9.422864
wagon       4wd            686.6  171.650000   2.251666
            fwd           2105.3  175.441667   9.097298
            rwd           1740.7  193.411111   5.268881

**Renaming grouped aggregation columns**

In [ ]:
df.groupby(
   ["body-style","drive-wheels"]).agg(
    # Get max of the price column for each group
    max_price=('price', max),
    # Get min of the price column for each group
    min_price=('price', min),
    # Get sum of the price column for each group
    total_price=('price', 'mean')

)

                          max_price  min_price   total_price
body-style  drive-wheels
convertible fwd               11595      11595  11595.000000
            rwd               37028      13495  23949.600000
hardtop     fwd                8249       8249   8249.000000
            rwd               45400       8449  24202.714286
hatchback   4wd               13207       7603  10405.000000
            fwd               18150       5118   8396.387755
            rwd               22018       8238  14278.263158
sedan       4wd               17450       9233  12647.333333
            fwd               23875       5499   9930.929825
            rwd               41315       6785  21711.833333
wagon       4wd               11694       7898   9095.750000
            fwd               18920       6918   9997.333333
            rwd               28248      12440  16994.222222

**Group-wise transformations**

In [ ]:
df["price"]=df["price"].transform(lambda x:x + x/10)
df.loc[:,'price']

0      14844.5
1      18150.0
2      18150.0
3      15345.0
4      19195.0
        ...
200    18529.5
201    20949.5
202    23633.5
203    24717.0
204    24887.5
Name: price, Length: 205, dtype: float64

Let's observe average price of cars for each grouping by body-style and drive-wheels

In [ ]:
df.groupby(["body-style","drive-wheels"])["price"].transform('mean')

0      26344.560000
1      26344.560000
2      15706.089474
3      10924.022807
4      13912.066667
           ...
200    23883.016667
201    23883.016667
202    23883.016667
203    23883.016667
204    23883.016667
Name: price, Length: 205, dtype: float64

In [ ]:
df["average-price"]=df.groupby(["body-style","drive-wheels"])["price"].transform('mean')
# selectiing columns body-style,drive-wheels,price and average-price
df.loc[:,["body-style","drive-wheels","price","average-price"]]

      body-style drive-wheels    price  average-price
0    convertible          rwd  14844.5   26344.560000
1    convertible          rwd  18150.0   26344.560000
2      hatchback          rwd  18150.0   15706.089474
3          sedan          fwd  15345.0   10924.022807
4          sedan          4wd  19195.0   13912.066667
..           ...          ...      ...            ...
200        sedan          rwd  18529.5   23883.016667
201        sedan          rwd  20949.5   23883.016667
202        sedan          rwd  23633.5   23883.016667
203        sedan          rwd  24717.0   23883.016667
204        sedan          rwd  24887.5   23883.016667

[205 rows x 4 columns]

**Pivot Tables and Cross-Tabulations**

In [ ]:
new_dataset1 = df.filter(["body-style","drive-wheels",
                          "length","width","height","curb-weight","price"],axis=1)
#simplest pivot table with dataframe df and index body-style
table = pd.pivot_table(new_dataset1, index =["body-style"])
table

             curb-weight     height      length         price      width
body-style
convertible  2801.666667  51.433333  170.383333  24079.550000  65.583333
hardtop      2810.625000  52.850000  176.937500  24429.350000  66.612500
hatchback    2348.185714  52.108571  166.592857  11055.314286  65.247143
sedan        2610.593750  54.337500  177.585417  15877.021875  66.260417
wagon        2784.240000  56.728000  181.304000  13609.156000  66.256000

In [ ]:
#pivot table with dataframe df and index body-style and drive-wheels
table = pd.pivot_table(new_dataset1, index =["body-style","drive-wheels"])
table

                          curb-weight     height  ...         price      width
body-style  drive-wheels                          ...
convertible fwd           2254.000000  55.600000  ...  12754.500000  64.200000
            rwd           2911.200000  50.600000  ...  26344.560000  65.860000
hardtop     fwd           2008.000000  53.300000  ...   9073.900000  63.800000
            rwd           2925.285714  52.785714  ...  26622.985714  67.014286
hatchback   4wd           2646.500000  53.850000  ...  11445.500000  65.850000
            fwd           2181.551020  52.442857  ...   9236.026531  64.671429
            rwd           2746.526316  51.063158  ...  15706.089474  66.668421
sedan       4wd           2573.000000  54.300000  ...  13912.066667  65.733333
            fwd           2298.228070  53.887719  ...  10924.022807  65.326316
            rwd           3108.305556  55.052778  ...  23883.016667  67.783333
wagon       4wd           2617.500000  57.000000  ...  10005.325000  64.500000
            fwd           2464.333333  56.008333  ...  10997.066667  65.533333
            rwd           3284.888889  57.566667  ...  18693.644444  68.000000

[13 rows x 5 columns]

In [ ]:
# import numpy for aggregration function
import numpy as np

#new data set with few columns
new_dataset3 = df.filter(["body-style","drive-wheels","price"],axis=1)

# pivot table with dataset new_dataset2
# values are the column in which aggregration function is to be applied
# index is column for grouping of data
# columns for specifying category of data
# aggfunc is the aggregration function to be applied
# fill_value to fill missing values
table = pd.pivot_table(new_dataset3, values='price', index=["body-style"],
                       columns=["drive-wheels"],aggfunc=np.mean,fill_value=0)
table

drive-wheels           4wd           fwd           rwd
body-style
convertible       0.000000  12754.500000  26344.560000
hardtop           0.000000   9073.900000  26622.985714
hatchback     11445.500000   9236.026531  15706.089474
sedan         13912.066667  10924.022807  23883.016667
wagon         10005.325000  10997.066667  18693.644444

In [ ]:
table = pd.pivot_table(new_dataset1, values=['price','height','width'],
                       index =["body-style","drive-wheels"],
                       aggfunc={'price': np.mean,'height': [min, max],'width': [min, max]},
                       fill_value=0)
table

                         height               price width
                            max   min          mean   max   min
body-style  drive-wheels
convertible fwd            55.6  55.6  12754.500000  64.2  64.2
            rwd            53.0  48.8  26344.560000  70.5  64.1
hardtop     fwd            53.3  53.3   9073.900000  63.8  63.8
            rwd            55.4  51.6  26622.985714  72.0  65.0
hatchback   4wd            55.7  52.0  11445.500000  67.9  63.8
            fwd            56.1  49.4   9236.026531  66.6  60.3
            rwd            54.8  49.6  15706.089474  72.3  64.0
sedan       4wd            54.3  54.3  13912.066667  66.4  65.4
            fwd            56.1  50.6  10924.022807  71.4  62.5
            rwd            56.7  47.8  23883.016667  71.7  61.8
wagon       4wd            59.1  54.9  10005.325000  65.4  63.6
            fwd            59.8  53.0  10997.066667  71.4  63.6
            rwd            58.7  54.1  18693.644444  70.3  66.5

**Cross-Tabulations**

In [ ]:
# apply pd.crosstab() function in data frame df
pd.crosstab(df["make"], df["body-style"])

body-style     convertible  hardtop  hatchback  sedan  wagon
make
alfa-romero              2        0          1      0      0
audi                     0        0          1      5      1
bmw                      0        0          0      8      0
chevrolet                0        0          2      1      0
dodge                    0        0          5      3      1
honda                    0        0          7      5      1
isuzu                    0        0          1      3      0
jaguar                   0        0          0      3      0
mazda                    0        0         10      7      0
mercedes-benz            1        2          0      4      1
mercury                  0        0          1      0      0
mitsubishi               0        0          9      4      0
nissan                   0        1          5      9      3
peugot                   0        0          0      7      4
plymouth                 0        0          4      2      1
porsche                  1        2          2      0      0
renault                  0        0          1      0      1
saab                     0        0          3      3      0
subaru                   0        0          3      5      4
toyota                   1        3         14     10      4
volkswagen               1        0          1      9      1
volvo                    0        0          0      8      3

In [ ]:
# apply margins and margins_name attribute to displays the row wise
# and column wise sum of the cross table
pd.crosstab(df["make"], df["body-style"],margins=True,margins_name="Total Made")

body-style     convertible  hardtop  hatchback  sedan  wagon  Total Made
make
alfa-romero              2        0          1      0      0           3
audi                     0        0          1      5      1           7
bmw                      0        0          0      8      0           8
chevrolet                0        0          2      1      0           3
dodge                    0        0          5      3      1           9
honda                    0        0          7      5      1          13
isuzu                    0        0          1      3      0           4
jaguar                   0        0          0      3      0           3
mazda                    0        0         10      7      0          17
mercedes-benz            1        2          0      4      1           8
mercury                  0        0          1      0      0           1
mitsubishi               0        0          9      4      0          13
nissan                   0        1          5      9      3          18
peugot                   0        0          0      7      4          11
plymouth                 0        0          4      2      1           7
porsche                  1        2          2      0      0           5
renault                  0        0          1      0      1           2
saab                     0        0          3      3      0           6
subaru                   0        0          3      5      4          12
toyota                   1        3         14     10      4          32
volkswagen               1        0          1      9      1          12
volvo                    0        0          0      8      3          11
Total Made               6        8         70     96     25         205

In [ ]:
pd.crosstab([df["make"],df["num-of-doors"]], [df["body-style"],df["drive-wheels"]],
            margins=True,margins_name="Total Made")

body-style                 convertible     hardtop      ... wagon         Total Made
drive-wheels                       fwd rwd     fwd rwd  ...   4wd fwd rwd
make          num-of-doors                              ...
alfa-romero   two                    0   2       0   0  ...     0   0   0          3
audi          four                   0   0       0   0  ...     0   1   0          5
              two                    0   0       0   0  ...     0   0   0          2
bmw           four                   0   0       0   0  ...     0   0   0          5
              two                    0   0       0   0  ...     0   0   0          3
chevrolet     four                   0   0       0   0  ...     0   0   0          1
              two                    0   0       0   0  ...     0   0   0          2
dodge         ?                      0   0       0   0  ...     0   0   0          1
              four                   0   0       0   0  ...     0   1   0          4
              two                    0   0       0   0  ...     0   0   0          4
honda         four                   0   0       0   0  ...     0   1   0          5
              two                    0   0       0   0  ...     0   0   0          8
isuzu         four                   0   0       0   0  ...     0   0   0          2
              two                    0   0       0   0  ...     0   0   0          2
jaguar        four                   0   0       0   0  ...     0   0   0          2
              two                    0   0       0   0  ...     0   0   0          1
mazda         ?                      0   0       0   0  ...     0   0   0          1
              four                   0   0       0   0  ...     0   0   0          7
              two                    0   0       0   0  ...     0   0   0          9
mercedes-benz four                   0   0       0   0  ...     0   0   1          5
              two                    0   1       0   2  ...     0   0   0          3
mercury       two                    0   0       0   0  ...     0   0   0          1
mitsubishi    four                   0   0       0   0  ...     0   0   0          4
              two                    0   0       0   0  ...     0   0   0          9
nissan        four                   0   0       0   0  ...     0   3   0          9
              two                    0   0       1   0  ...     0   0   0          9
peugot        four                   0   0       0   0  ...     0   0   4         11
plymouth      four                   0   0       0   0  ...     0   1   0          4
              two                    0   0       0   0  ...     0   0   0          3
porsche       two                    0   1       0   2  ...     0   0   0          5
renault       four                   0   0       0   0  ...     0   1   0          1
              two                    0   0       0   0  ...     0   0   0          1
saab          four                   0   0       0   0  ...     0   0   0          3
              two                    0   0       0   0  ...     0   0   0          3
subaru        four                   0   0       0   0  ...     2   2   0          9
              two                    0   0       0   0  ...     0   0   0          3
toyota        four                   0   0       0   0  ...     2   1   1         18
              two                    0   1       0   3  ...     0   0   0         14
volkswagen    four                   0   0       0   0  ...     0   1   0          8
              two                    1   0       0   0  ...     0   0   0          4
volvo         four                   0   0       0   0  ...     0   0   3         11
Total Made                           1   5       1   7  ...     4  12   9        205

[42 rows x 14 columns]

In [ ]:
# rename the columns and row index for better understanding of crosstab
pd.crosstab([df["make"],df["num-of-doors"]], [df["body-style"],df["drive-wheels"]],
            rownames=['Auto Manufacturer', "Doors"],
            colnames=['Body Style', "Drive Type"],
            margins=True,margins_name="Total Made").head()

Body Style              convertible     hardtop      ... wagon         Total Made
Drive Type                      fwd rwd     fwd rwd  ...   4wd fwd rwd
Auto Manufacturer Doors                              ...
alfa-romero       two             0   2       0   0  ...     0   0   0          3
audi              four            0   0       0   0  ...     0   1   0          5
                  two             0   0       0   0  ...     0   0   0          2
bmw               four            0   0       0   0  ...     0   0   0          5
                  two             0   0       0   0  ...     0   0   0          3

[5 rows x 14 columns]

In [ ]:
# values are the column in which aggregration function is to be applied
# aggfunc is the aggregration function to be applied
# round() to round the output

pd.crosstab(df["make"], df["body-style"],values=df["curb-weight"],
            aggfunc='mean').round(0)

body-style     convertible  hardtop  hatchback   sedan   wagon
make
alfa-romero         2548.0      NaN     2823.0     NaN     NaN
audi                   NaN      NaN     3053.0  2720.0  2954.0
bmw                    NaN      NaN        NaN  2929.0     NaN
chevrolet              NaN      NaN     1681.0  1909.0     NaN
dodge                  NaN      NaN     2132.0  2056.0  2535.0
honda                  NaN      NaN     1970.0  2289.0  2024.0
isuzu                  NaN      NaN     2734.0  2040.0     NaN
jaguar                 NaN      NaN        NaN  4027.0     NaN
mazda                  NaN      NaN     2254.0  2361.0     NaN
mercedes-benz       3685.0   3605.0        NaN  3731.0  3750.0
mercury                NaN      NaN     2910.0     NaN     NaN
mitsubishi             NaN      NaN     2377.0  2394.0     NaN
nissan                 NaN   2008.0     2740.0  2238.0  2452.0
peugot                 NaN      NaN        NaN  3143.0  3358.0
plymouth               NaN      NaN     2208.0  2090.0  2535.0
porsche             2800.0   2756.0     3072.0     NaN     NaN
renault                NaN      NaN     2460.0     NaN  2579.0
saab                   NaN      NaN     2724.0  2767.0     NaN
subaru                 NaN      NaN     2137.0  2314.0  2454.0
toyota              2975.0   2585.0     2370.0  2338.0  2708.0
volkswagen          2254.0      NaN     2221.0  2342.0  2563.0
volvo                  NaN      NaN        NaN  3023.0  3078.0

In [ ]:
# top ten output that represents the percentage of occurrence of the combination
pd.crosstab(df["make"], df["body-style"],normalize=True).head(10)

body-style     convertible   hardtop  hatchback     sedan     wagon
make
alfa-romero       0.009756  0.000000   0.004878  0.000000  0.000000
audi              0.000000  0.000000   0.004878  0.024390  0.004878
bmw               0.000000  0.000000   0.000000  0.039024  0.000000
chevrolet         0.000000  0.000000   0.009756  0.004878  0.000000
dodge             0.000000  0.000000   0.024390  0.014634  0.004878
honda             0.000000  0.000000   0.034146  0.024390  0.004878
isuzu             0.000000  0.000000   0.004878  0.014634  0.000000
jaguar            0.000000  0.000000   0.000000  0.014634  0.000000
mazda             0.000000  0.000000   0.048780  0.034146  0.000000
mercedes-benz     0.004878  0.009756   0.000000  0.019512  0.004878

In [ ]:
import csv, json
with open("Books_data.csv") as csvf:
    read1=csv.DictReader(csvf)
    data=[item for item in read1]
print(data)
with open("Books.json","w") as jsonf:
     json.dump(data,jsonf)

[{'Serial No.': '1', 'title': 'Steve Jobs', 'author': 'Walter Issacson', 'category': 'Biography', 'status': 'issued'}, {'Serial No.': '2', 'title': 'Discovery of India', 'author': 'Jawaharlal Nehru', 'category': 'History', 'status': 'issued'}, {'Serial No.': '3', 'title': 'My Experiments with Truth', 'author': 'Mahatma Gandhi', 'category': 'Autobiography', 'status': 'issued'}, {'Serial No.': '4', 'title': 'Object Oriented Programming with C++', 'author': 'E Balagurusamy', 'category': 'Education', 'status': 'issued'}, {'Serial No.': '5', 'title': 'Thinking with type', 'author': 'Ellen Lupton', 'category': 'Arts', 'status': 'issued'}, {'Serial No.': '6', 'title': "The Photographer's", 'author': 'Lindsay Adler', 'category': 'Photography', 'status': 'issued'}, {'Serial No.': '7', 'title': 'Think and Grow', 'author': 'Napoleon Hill', 'category': 'Economics', 'status': 'issued'}, {'Serial No.': '8', 'title': 'The Fifth Discipline : The Art', 'author': 'Peter M.Senge', 'category': 'Management', 'status': 'issued'}, {'Serial No.': '9', 'title': 'A Theory of Justice', 'author': 'John Rawls', 'category': 'Law', 'status': 'issued'}, {'Serial No.': '10', 'title': 'Eat to Live', 'author': 'Joel Fuhrman', 'category': 'Health', 'status': 'issued'}, {'Serial No.': '11', 'title': 'City of Heavenly Fire', 'author': 'Cassandra Clare', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '12', 'title': 'Da Vinci Code', 'author': 'Dan Brown', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '13', 'title': 'War and Peace', 'author': 'Leo Tolstoy', 'category': 'Philosophical fiction', 'status': 'issued'}, {'Serial No.': '14', 'title': 'Python For All', 'author': 'John Shovic', 'category': 'Education', 'status': 'available'}, {'Serial No.': '15', 'title': 'Automate The Boring Stuff With Python', 'author': 'Al Sweigart', 'category': 'Education', 'status': 'available'}, {'Serial No.': '16', 'title': 'Wings Of Fire', 'author': 'APJ Abdul Kalam', 'category': 'Autobiography', 'status': 'available'}, {'Serial No.': '17', 'title': 'Ikigai', 'author': 'Hector Garcia', 'category': 'Personal Development', 'status': 'available'}, {'Serial No.': '18', 'title': 'Who Will Cry When You Will Die', 'author': 'Robin Sharma', 'category': 'Personal Development', 'status': 'available'}, {'Serial No.': '19', 'title': 'Rich Dad Poor Dad', 'author': 'Robert T. Kiyosaki', 'category': 'Business', 'status': 'available'}, {'Serial No.': '20', 'title': 'Immortals of Meluha', 'author': 'Amish Tirpathi', 'category': 'High Fantasy', 'status': 'available'}, {'Serial No.': '21', 'title': 'A Brief History Of Time', 'author': 'Stephen Hawking', 'category': 'SPACE', 'status': 'issued'}, {'Serial No.': '22', 'title': 'I Know Why The Cage Bird Sings', 'author': 'Maya Anguelo', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '23', 'title': 'Lord Of Files', 'author': 'William Golding', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '24', 'title': 'Loara Dune', 'author': 'R. D Blackmore', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '25', 'title': 'Jamacia Inn', 'author': 'Daphne', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '26', 'title': 'Kidnapped', 'author': 'Robert Louis', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '27', 'title': 'Treasure Island', 'author': 'Robert Louis', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '28', 'title': 'The Call Of Wild', 'author': 'Jack London', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '29', 'title': 'Charlottes Web', 'author': 'E. B White', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '30', 'title': 'The Wind In Willows', 'author': 'Kenneth Grahame', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '31', 'title': 'Being and Time', 'author': 'Martin Heldegger', 'category': 'Philosophy', 'status': 'available'}, {'Serial No.': '32', 'title': 'The Republic', 'author': 'Rocha Pereia', 'category': 'Philosophy', 'status': 'issued'}, {'Serial No.': '33', 'title': 'Critique For Pure Reason', 'author': 'Paul Guyer', 'category': 'Philosophy', 'status': 'available'}, {'Serial No.': '34', 'title': 'The Prince', 'author': 'Rufus Godwin', 'category': 'Philosophy', 'status': 'available'}, {'Serial No.': '35', 'title': 'Ethics', 'author': 'Stuart Hampshire', 'category': 'Philosophy', 'status': 'available'}, {'Serial No.': '36', 'title': 'Long Walk To Freedom', 'author': 'Nelson Mandela', 'category': 'Autobiography', 'status': 'available'}, {'Serial No.': '37', 'title': 'The Dairy Of Young Girl', 'author': 'Anne Frank', 'category': 'Autobiography', 'status': 'available'}, {'Serial No.': '38', 'title': 'Mark Twain', 'author': 'Mark Twain', 'category': 'Autobiography', 'status': 'available'}, {'Serial No.': '39', 'title': 'Mein Kampf', 'author': 'Adolf Hitler', 'category': 'Autobiography', 'status': 'available'}, {'Serial No.': '40', 'title': 'Freakonomics', 'author': 'Steveb D.Levit', 'category': 'Economics', 'status': 'issued'}, {'Serial No.': '41', 'title': 'Thinking Fast and Slow', 'author': 'Daniel Kahneman', 'category': 'Economics', 'status': 'available'}, {'Serial No.': '42', 'title': 'Tell You About Capitalism', 'author': 'HA-Joon Chang', 'category': 'Economics', 'status': 'available'}, {'Serial No.': '43', 'title': 'Animal Spirits', 'author': 'Akerlof and Shiller', 'category': 'Economics', 'status': 'available'}, {'Serial No.': '44', 'title': 'The Black Swan', 'author': 'Nassim Nicholas Taleb', 'category': 'Economics', 'status': 'issued'}, {'Serial No.': '45', 'title': '1984', 'author': 'George Orwell', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '46', 'title': 'The Lord Of Wings ', 'author': 'J.R.R.Tolken', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '47', 'title': 'The Night Circus', 'author': 'Erin Morgenstern', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '48', 'title': 'Harry Potter', 'author': 'J.K.Rowling', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '49', 'title': 'Don Quixote', 'author': 'Miguel de Cervantes', 'category': 'Fiction', 'status': 'available'}, {'Serial No.': '50', 'title': 'History Of 20th Century', 'author': 'Martin Gilbert', 'category': 'History', 'status': 'available'}, {'Serial No.': '51', 'title': 'Guns,Germs,and Steel', 'author': 'Jared Daimond', 'category': 'History', 'status': 'issued'}, {'Serial No.': '52', 'title': 'A World lit Only by Fire', 'author': 'William Manchestar', 'category': 'History', 'status': 'issued'}, {'Serial No.': '53', 'title': 'The Crusades ', 'author': 'Thomas Asbridge', 'category': 'History', 'status': 'available'}, {'Serial No.': '54', 'title': 'Over The Edge Of The World', 'author': 'Laurence', 'category': 'History', 'status': 'available'}, {'Serial No.': '55', 'title': 'A Beautiful Mind ', 'author': 'Sylvia Nasar', 'category': 'Biography', 'status': 'available'}, {'Serial No.': '56', 'title': 'The Enigma', 'author': 'Andrew Hodges', 'category': 'Biography', 'status': 'available'}, {'Serial No.': '57', 'title': 'Alexander Hamilton', 'author': 'Ron Chernow', 'category': 'Biography', 'status': 'available'}, {'Serial No.': '58', 'title': 'Barracoon', 'author': 'Zora Neale Hurston', 'category': 'Biography', 'status': 'available'}, {'Serial No.': '59', 'title': 'CHURCHILL : A Life', 'author': 'MArtin Glibert', 'category': 'Biography', 'status': 'available'}, {'Serial No.': '60', 'title': 'Adventures of Huckleberry Finn', 'author': 'Mark Twain', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '61', 'title': 'Das Kapital', 'author': 'Karl Marx', 'category': 'Non-fiction', 'status': 'available'}, {'Serial No.': '62', 'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '63', 'title': 'Pride and Prejudice', 'author': 'Jane Austen', 'category': 'Romance', 'status': 'Available'}, {'Serial No.': '64', 'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '65', 'title': 'Moby-Dick', 'author': 'Herman Melville', 'category': 'Adventure', 'status': 'Available'}, {'Serial No.': '66', 'title': "Gulliver's Travels", 'author': 'Jonathan Swift', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '67', 'title': 'The Catcher in the Rye', 'author': 'J.D. Salinger', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '68', 'title': 'Brave New World', 'author': 'Aldous Huxley', 'category': 'Science Fiction', 'status': 'issued'}, {'Serial No.': '69', 'title': 'The Odyssey', 'author': 'Homer', 'category': 'Epic', 'status': 'Available'}, {'Serial No.': '70', 'title': 'Crime and Punishment', 'author': 'Fyodor Dostoevsky', 'category': 'Psychological', 'status': 'Available'}, {'Serial No.': '71', 'title': 'The Hobbit', 'author': 'J.R.R. Tolkien', 'category': 'Fantasy', 'status': 'issued'}, {'Serial No.': '72', 'title': 'The Lord of the Rings', 'author': 'J.R.R. Tolkien', 'category': 'Fantasy', 'status': 'Available'}, {'Serial No.': '73', 'title': 'Animal Farm', 'author': 'George Orwell', 'category': 'Political', 'status': 'Available'}, {'Serial No.': '74', 'title': 'Les Misérables', 'author': 'Victor Hugo', 'category': 'History', 'status': 'issued'}, {'Serial No.': '75', 'title': 'The Picture of Dorian Gray', 'author': 'Oscar Wilde', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '76', 'title': 'The Chronicles of Narnia', 'author': 'C.S. Lewis', 'category': 'Fantasy', 'status': 'issued'}, {'Serial No.': '77', 'title': 'The Alchemist', 'author': 'Paulo Coelho', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '78', 'title': 'Fahrenheit 451', 'author': 'Ray Bradbury', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '79', 'title': 'The Road', 'author': 'Cormac McCarthy', 'category': 'Post-apocalyptic', 'status': 'issued'}, {'Serial No.': '80', 'title': 'The Shining', 'author': 'Stephen King', 'category': 'Horror', 'status': 'Available'}, {'Serial No.': '81', 'title': 'The Book Thief', 'author': 'Markus Zusak', 'category': 'History', 'status': 'issued'}, {'Serial No.': '82', 'title': 'The Secret Garden', 'author': 'Frances Hodgson Burnett', 'category': 'Children’s', 'status': 'Available'}, {'Serial No.': '83', 'title': 'Gone with the Wind', 'author': 'Margaret Mitchell', 'category': 'History', 'status': 'issued'}, {'Serial No.': '84', 'title': 'The Diary of Anne Frank', 'author': 'Anne Frank', 'category': 'Biography', 'status': 'Available'}, {'Serial No.': '85', 'title': 'The Hunger Games', 'author': 'Suzanne Collins', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '86', 'title': 'A Tale of Two Cities', 'author': 'Charles Dickens', 'category': 'History', 'status': 'Available'}, {'Serial No.': '87', 'title': 'The Kite Runner', 'author': 'Khaled Hosseini', 'category': 'History', 'status': 'issued'}, {'Serial No.': '88', 'title': 'The Little Prince', 'author': 'Antoine de Saint-Exupéry', 'category': 'Children’s', 'status': 'Available'}, {'Serial No.': '89', 'title': 'The Giver', 'author': 'Lois Lowry', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '90', 'title': 'The Fault in Our Stars', 'author': 'John Green', 'category': 'Romance', 'status': 'issued'}, {'Serial No.': '91', 'title': 'The Outsiders', 'author': 'S.E. Hinton', 'category': 'Coming-of-age', 'status': 'Available'}, {'Serial No.': '92', 'title': 'The Bell Jar', 'author': 'Sylvia Plath', 'category': 'Psychological', 'status': 'issued'}, {'Serial No.': '93', 'title': 'The Scarlet Letter', 'author': 'Nathaniel Hawthorne', 'category': 'History', 'status': 'Available'}, {'Serial No.': '94', 'title': 'The Girl on the Train', 'author': 'Paula Hawkins', 'category': 'Thriller', 'status': 'Available'}, {'Serial No.': '95', 'title': 'The Goldfinch', 'author': 'Donna Tartt', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '96', 'title': 'The Invisible Man', 'author': 'H.G. Wells', 'category': 'Science Fiction', 'status': 'Available'}, {'Serial No.': '97', 'title': "The Handmaid's Tale", 'author': 'Margaret Atwood', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '98', 'title': 'The Moon and Sixpence', 'author': 'W. Somerset Maugham', 'category': 'Fiction', 'status': 'Available'}, {'Serial No.': '99', 'title': 'A Thousand Splendid Suns', 'author': ' Khaled Hosseini', 'category': 'Fiction', 'status': 'issued'}, {'Serial No.': '100', 'title': 'Doctor Zhivago', 'author': 'Boris Pasternak', 'category': 'History', 'status': 'Available'}, {'Serial No.': '101', 'title': 'The Man Who Mistook His Wife for a Hat', 'author': 'Oliver Sacks', 'category': 'Non-fiction', 'status': 'issued'}, {'Serial No.': '102', 'title': 'And the Mountains Echoed', 'author': ' Khaled Hosseini', 'category': 'Fiction', 'status': ' issued'}, {'Serial No.': '103', 'title': 'Hind Swaraj', 'author': 'Mahatama Gandhi', 'category': 'Non-fiction', 'status': ' Avaialble'}]